apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: credit-account-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: credit-account-app
    spec:
      containers:
      - name: credit-account-app
        image: IMAGE 
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: credit-account-service
  labels:
    app: credit-account-service
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 32426
  selector:
    app: credit-account-app
