---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
        version: v1
    spec:
      containers:
        - image: mongo
          name: mongo
          ports:
            - containerPort: 27017
              name: mongocontainer
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo
