apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-details-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-details-app
  template:
    metadata:
      labels:
        app: account-details-app
    spec:
      containers:
      - name: account-details-app
        image: IMAGE      
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: account-details-service
  labels:
    app: account-details-service
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 32424
  selector:
    app: account-details-app
